### Get all decks
GET http://localhost:3001/api/decks

### Get deck by id
GET http://localhost:3001/api/decks/28

### Register a new user
POST http://localhost:3001/api/registration
content-type: application/json

{
    "email": "testing@example.com",
    "password": "test"
}

### Login with existing user
POST http://localhost:3001/api/login
content-type: application/json

{
    "email": "testing@example.com",
    "password": "test"
}

### Fetch deck by user id (broken)
GET http://localhost:3001/api/decks/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0ZXN0aW5nQGV4YW1wbGUuY29tIiwiaWF0IjoxNjA0ODk0MzUxfQ.a-4tZqNQbOv9pTPBQdzwHS_8687OWmVyAX-xYSwS3Lc

### Create deck
POST http://localhost:3001/api/deck
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0ZXN0aW5nQGV4YW1wbGUuY29tIiwiaWF0IjoxNjA0ODk0MzUxfQ.a-4tZqNQbOv9pTPBQdzwHS_8687OWmVyAX-xYSwS3Lc

{
    "title": "deck test",
    "sections": [
        {
            "title": "section 1",
            "cards": [
                {
                    "front": "# card 1",
                    "back": "# card back 1",
                    "meta": "card example",
                    "language": "markdown"
                }
            ]
        }
    ]
}

### export deck by id
GET http://localhost:3001/api/decks/exports/16

### update deck by id
PATCH http://localhost:3001/api/deck/28
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0ZXN0aW5nQGV4YW1wbGUuY29tIiwiaWF0IjoxNjA0ODk0MzUxfQ.a-4tZqNQbOv9pTPBQdzwHS_8687OWmVyAX-xYSwS3Lc

{
    "deck": {
        "title": "deck TEST"
    },
    "card": {
        "89": {
            "id": "89",
            "front": "card 1 TEST",
            "meta": "card example TEST"
        }
    },
    "section": {
        "38": {
            "id": "38",
            "title": "section 1 TEST"
        }
    }
}

### get deck with id 28
GET http://localhost:3001/api/decks/28

### delete deck by id
DELETE http://localhost:3001/api/deck/20

### delete section by id
DELETE http://localhost:3001/api/deck/section/40

### test endpoint below
GET http://localhost:3001/api/test
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ0ZXN0aW5nQGV4YW1wbGUuY29tIiwiaWF0IjoxNjA0ODk0MzUxfQ.a-4tZqNQbOv9pTPBQdzwHS_8687OWmVyAX-xYSwS3Lc

{
    "email": "testing@example.com",
    "password": "test"
}

### register user

POST http://localhost:3001/api/registration
content-type: application/json

{
    "email": "test@test.com",
    "password": "test"
}

### login user

POST http://localhost:3001/api/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "test"
}